rivers = ['Yellow River', 'Yangtze', 'Langcang', 'Huaihe']
print(rivers)
rivers.sort()
print(rivers)
rivers.sort(reverse=True)
print(rivers)
print(sorted(rivers))
print(sorted(rivers, reverse=True))
rivers.reverse()
print(rivers)
rivers.reverse()
print(rivers)
print(len(rivers))
print(rivers)