tourist_attractions = ['Tibet', 'Roman', 'Italy', 'Paris', 'Tokyo']
print(tourist_attractions)
print(sorted(tourist_attractions))
print(tourist_attractions)
print(sorted(tourist_attractions, reverse=True))
print(tourist_attractions)
tourist_attractions.reverse()
print(tourist_attractions)
tourist_attractions.reverse()
print(tourist_attractions)
tourist_attractions.sort()
print(tourist_attractions)
tourist_attractions.sort(reverse=True)
print(tourist_attractions)